# -*- coding: utf-8 -*-
"""ec_training_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JH6zDTPnKTK1TAM-XlkqUFzlskUj_II1
"""

# ============================================================
# CELL 0 — SETUP (FIXED)
# torch 2.11+cu130 is already installed correctly on Kaggle T4.
# Do NOT uninstall/reinstall torch — that caused the original failure.
# Just install the extras.
# ============================================================
import subprocess, sys

def pip_install(*packages):
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", *packages])

pip_install("codecarbon", "xgboost", "joblib", "prettytable")
pip_install("--no-deps", "timm")
pip_install("--no-deps", "grad-cam")

import torch
print(torch.__version__)
print("CUDA:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

# ============================================================
# Carbon-Aware Image Classification using ACO on CIFAR-100
# Kaggle Notebook (Single Script Format) — Phase 1
# ============================================================

import subprocess, sys

# ==============================================================
# FIX-FLUSH: Patch builtins.print so every print() auto-flushes.
# Must be done at the very top before any print() calls.
# Kaggle OutStream has no .reconfigure() so we cannot use that.
# ==============================================================
import builtins as _builtins
_real_print = _builtins.print
def print(*args, **kwargs):
    kwargs.setdefault("flush", True)
    _real_print(*args, **kwargs)

# ==============================================================
# SECTION 0B: CORE IMPORTS
# ==============================================================
import os, json, time, math, random, shutil, zipfile, warnings, logging
import numpy as np
import pandas as pd
from pathlib import Path
from copy import deepcopy
from datetime import datetime
from collections import defaultdict

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

# torch.amp (not torch.cuda.amp which is deprecated in PyTorch >= 2.0)
from torch.amp import GradScaler, autocast

from torch.utils.data import DataLoader, Subset, random_split

import torchvision
import torchvision.transforms as T
from torchvision.datasets import CIFAR100

import timm
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.svm import LinearSVC          # FIX: Use LinearSVC (10-50x faster than SVC rbf)
from sklearn.calibration import CalibratedClassifierCV
from sklearn.ensemble import RandomForestClassifier

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_recall_fscore_support, accuracy_score
from xgboost import XGBClassifier
import joblib

from codecarbon import EmissionsTracker
from prettytable import PrettyTable

warnings.filterwarnings("ignore")

# Suppress CodeCarbon + pynvml noise
for _noisy_logger in ("codecarbon", "codecarbon.emissions_tracker",
                      "codecarbon.core.gpu_nvidia", "pynvml"):
    logging.getLogger(_noisy_logger).setLevel(logging.CRITICAL)

# ==============================================================
# SECTION 1: GLOBAL CONFIG & REPRODUCIBILITY
# ==============================================================
SEED           = 42
EPOCHS         = 70            # 40 epochs fits safely within Kaggle's 9-hr session limit
BATCH_SIZE     = 128
VAL_SPLIT      = 0.1
NUM_CLASSES    = 100
PCA_COMPONENTS = 100           # FIX: was blank/missing in previous version
ACO_ITERATIONS = 15
ACO_ANTS       = 10
LAMBDA_CARBON  = 0.5
DATA_DIR       = "./data"
ARTIFACT_DIR   = "./runs_v2"
MAX_SAMPLES    = 15000         # Classical ML trained on this many samples (speed vs accuracy tradeoff)

def _validated_device():
    """Check CUDA is actually usable before committing to it."""
    if not torch.cuda.is_available():
        return torch.device("cpu")
    try:
        _t = torch.zeros(1, device="cuda") + 1
        del _t
        torch.cuda.empty_cache()
        return torch.device("cuda")
    except Exception as _e:
        print(f"[WARN] CUDA unusable ({type(_e).__name__}: {_e}). Falling back to CPU.")
        return torch.device("cpu")

DEVICE      = _validated_device()
DEVICE_TYPE = DEVICE.type   # "cuda" or "cpu"

CIFAR100_MEAN = (0.5071, 0.4867, 0.4408)
CIFAR100_STD  = (0.2675, 0.2565, 0.2761)

SUPERCLASS_MAPPING = {
    "aquatic_mammals":          [4, 30, 55, 72, 95],
    "fish":                     [1, 32, 67, 73, 91],
    "flowers":                  [54, 62, 70, 82, 92],
    "food_containers":          [9, 10, 16, 28, 61],
    "fruit_and_vegetables":     [0, 51, 53, 57, 83],
    "household_electrical":     [22, 39, 40, 86, 87],
    "household_furniture":      [5, 20, 25, 84, 94],
    "insects":                  [6, 7, 14, 18, 24],
    "large_carnivores":         [3, 42, 43, 88, 97],
    "large_man-made_outdoor":   [12, 17, 37, 68, 76],
    "large_natural_outdoor":    [23, 33, 49, 60, 71],
    "large_omnivores":          [15, 19, 21, 31, 38],
    "medium_mammals":           [34, 63, 64, 66, 75],
    "non-insect_invertebrates": [26, 45, 77, 79, 99],
    "people":                   [2, 11, 35, 46, 98],
    "reptiles":                 [27, 29, 44, 78, 93],
    "small_mammals":            [36, 50, 65, 74, 80],
    "trees":                    [47, 52, 56, 59, 96],
    "vehicles_1":               [8, 13, 48, 58, 90],
    "vehicles_2":               [41, 69, 81, 85, 89],
}

def set_seed(seed=SEED):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_seed()
Path(ARTIFACT_DIR).mkdir(parents=True, exist_ok=True)
Path(DATA_DIR).mkdir(parents=True, exist_ok=True)

print(f"[INFO] Device: {DEVICE}")
print(f"[INFO] Artifacts will be saved to: {ARTIFACT_DIR}")

# ==============================================================
# SECTION 2: DATA PIPELINE
# ==============================================================

train_transform = T.Compose([
    T.RandomCrop(32, padding=4),
    T.RandomHorizontalFlip(),
    T.AutoAugment(T.AutoAugmentPolicy.CIFAR10),
    T.ToTensor(),
    T.Normalize(CIFAR100_MEAN, CIFAR100_STD),
    T.RandomErasing(p=0.2),
])

test_transform = T.Compose([
    T.ToTensor(),
    T.Normalize(CIFAR100_MEAN, CIFAR100_STD),
])

print("[INFO] Downloading CIFAR-100...")
full_train_dataset = CIFAR100(root=DATA_DIR, train=True,  download=True, transform=train_transform)
test_dataset       = CIFAR100(root=DATA_DIR, train=False, download=True, transform=test_transform)
embed_dataset      = CIFAR100(root=DATA_DIR, train=True,  download=False, transform=test_transform)

n_val   = int(len(full_train_dataset) * VAL_SPLIT)
n_train = len(full_train_dataset) - n_val
g       = torch.Generator().manual_seed(SEED)
g_embed = torch.Generator().manual_seed(SEED)   # separate generator so embed split == train split

train_dataset,       val_dataset = random_split(full_train_dataset, [n_train, n_val], generator=g)
embed_train_dataset, _           = random_split(embed_dataset,      [n_train, n_val], generator=g_embed)

train_loader = DataLoader(train_dataset,       batch_size=BATCH_SIZE, shuffle=True,  num_workers=2, pin_memory=True)
val_loader   = DataLoader(val_dataset,         batch_size=BATCH_SIZE, shuffle=False, num_workers=2, pin_memory=True)
test_loader  = DataLoader(test_dataset,        batch_size=BATCH_SIZE, shuffle=False, num_workers=2, pin_memory=True)
embed_loader = DataLoader(embed_train_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=2, pin_memory=True)

print(f"[INFO] Train: {n_train} | Val: {n_val} | Test: {len(test_dataset)}")

# ==============================================================
# SECTION 3: CUTMIX IMPLEMENTATION
# ==============================================================

def rand_bbox(size, lam):
    W, H = size[2], size[3]
    cut_ratio = math.sqrt(1.0 - lam)
    cut_w = int(W * cut_ratio)
    cut_h = int(H * cut_ratio)
    cx = random.randint(0, W)
    cy = random.randint(0, H)
    x1 = max(cx - cut_w // 2, 0)
    y1 = max(cy - cut_h // 2, 0)
    x2 = min(cx + cut_w // 2, W)
    y2 = min(cy + cut_h // 2, H)
    return x1, y1, x2, y2

def cutmix_batch(images, labels, alpha=1.0, p=0.5):
    if random.random() > p:
        return images, labels, labels, 1.0
    lam = np.random.beta(alpha, alpha)
    bs  = images.size(0)
    idx = torch.randperm(bs)
    x1, y1, x2, y2 = rand_bbox(images.size(), lam)
    images[:, :, x1:x2, y1:y2] = images[idx, :, x1:x2, y1:y2]
    lam = 1 - ((x2 - x1) * (y2 - y1)) / (images.size(-1) * images.size(-2))
    return images, labels, labels[idx], lam

# ==============================================================
# SECTION 4: MODEL DEFINITIONS
# ==============================================================

def build_resnet50():
    return timm.create_model("resnet50", pretrained=True, num_classes=NUM_CLASSES).to(DEVICE)

def build_efficientnet_b3():
    return timm.create_model("efficientnet_b3", pretrained=True, num_classes=NUM_CLASSES).to(DEVICE)

def build_vit_tiny():
    return timm.create_model("vit_tiny_patch16_224", pretrained=True, num_classes=NUM_CLASSES).to(DEVICE)

MODEL_REGISTRY = {
    "resnet50":        build_resnet50,
    "efficientnet_b3": build_efficientnet_b3,
    "vit_tiny":        build_vit_tiny,
}

# ==============================================================
# SECTION 5: TRAINING UTILITIES
# ==============================================================

def get_optimizer_scheduler(model, train_steps, lr=1e-3, wd=1e-4):
    optimizer = optim.AdamW(model.parameters(), lr=lr, weight_decay=wd)
    scheduler = optim.lr_scheduler.OneCycleLR(
        optimizer,
        max_lr=lr,
        total_steps=train_steps,
        pct_start=0.1,
        anneal_strategy="cos",
    )
    return optimizer, scheduler

def label_smooth_loss(pred, y_a, y_b, lam, smoothing=0.1):
    criterion = nn.CrossEntropyLoss(label_smoothing=smoothing)
    return lam * criterion(pred, y_a) + (1 - lam) * criterion(pred, y_b)

@torch.no_grad()
def evaluate(model, loader, use_resize=False):
    model.eval()
    correct1 = correct5 = total = 0
    latencies = []
    for images, labels in loader:
        if use_resize:
            images = F.interpolate(images, size=224, mode="bilinear", align_corners=False)
        images, labels = images.to(DEVICE), labels.to(DEVICE)
        t0  = time.perf_counter()
        out = model(images)
        latencies.append((time.perf_counter() - t0) / images.size(0) * 1000)
        _, pred5 = out.topk(5, dim=1)
        correct5 += pred5.eq(labels.view(-1, 1).expand_as(pred5)).any(dim=1).sum().item()
        correct1 += pred5[:, 0].eq(labels).sum().item()
        total    += labels.size(0)
    return correct1 / total, correct5 / total, float(np.mean(latencies))

@torch.no_grad()
def per_class_accuracy(model, loader, use_resize=False):
    model.eval()
    correct = np.zeros(NUM_CLASSES)
    counts  = np.zeros(NUM_CLASSES)
    for images, labels in loader:
        if use_resize:
            images = F.interpolate(images, size=224, mode="bilinear", align_corners=False)
        images = images.to(DEVICE)
        out    = model(images)
        preds  = out.argmax(dim=1).cpu().numpy()
        labs   = labels.numpy()
        for p, l in zip(preds, labs):
            counts[l] += 1
            if p == l:
                correct[l] += 1
    return (correct / np.maximum(counts, 1)).tolist()

def model_size_mb(model):
    tmp = "/tmp/tmp_model.pt"
    torch.save(model.state_dict(), tmp)
    size = os.path.getsize(tmp) / 1e6
    os.remove(tmp)
    return round(size, 2)

def get_all_preds_labels(model, loader, use_resize=False):
    model.eval()
    all_preds, all_labels = [], []
    with torch.no_grad():
        for images, labels in loader:
            if use_resize:
                images = F.interpolate(images, size=224, mode="bilinear", align_corners=False)
            out   = model(images.to(DEVICE))
            preds = out.argmax(dim=1).cpu().numpy()
            all_preds.extend(preds.tolist())
            all_labels.extend(labels.numpy().tolist())
    return np.array(all_preds), np.array(all_labels)

# ==============================================================
# SECTION 6: DEEP LEARNING TRAINING LOOP WITH CARBON TRACKING
# ==============================================================

def train_dl_model(model_name, epochs=EPOCHS):
    print(f"\n{'='*60}")
    print(f"[TRAIN] {model_name.upper()} | Epochs: {epochs}")
    print(f"{'='*60}")

    is_vit   = "vit" in model_name
    model    = MODEL_REGISTRY[model_name]()
    n_params = sum(p.numel() for p in model.parameters()) / 1e6
    print(f"[INFO] Parameters: {n_params:.2f}M")

    steps_per_epoch      = len(train_loader)
    total_steps          = steps_per_epoch * epochs
    optimizer, scheduler = get_optimizer_scheduler(model, total_steps)
    scaler               = GradScaler(device=DEVICE_TYPE)

    training_curves   = {"train_loss": [], "val_acc1": [], "val_acc5": [], "epoch_emission_kg": []}
    best_val_acc      = 0.0
    best_state        = None
    ckpt_path         = f"{ARTIFACT_DIR}/{model_name}_best.pt"
    total_emission_kg = 0.0

    _gpu_ids = [] if DEVICE_TYPE == "cpu" else None
    outer_tracker = EmissionsTracker(
        project_name=f"{model_name}_total",
        output_dir=ARTIFACT_DIR,
        output_file=f"{model_name}_total_emissions.csv",
        log_level="error",
        save_to_file=True,
        gpu_ids=_gpu_ids,
    )
    outer_tracker.start()

    # Resume from checkpoint if session was interrupted
    start_epoch = 1
    for resume_ep in range((epochs // 10) * 10, 0, -10):
        resume_ckpt = f"{ARTIFACT_DIR}/{model_name}_epoch{resume_ep}.pt"
        if os.path.exists(resume_ckpt):
            print(f"[RESUME] Found checkpoint at epoch {resume_ep}: {resume_ckpt}")
            ckpt_data = torch.load(resume_ckpt, map_location=DEVICE, weights_only=True)
            model.load_state_dict(ckpt_data["model_state_dict"])
            try:
                optimizer.load_state_dict(ckpt_data["optimizer_state_dict"])
            except Exception:
                pass
            best_val_acc      = ckpt_data.get("best_val_acc", 0.0)
            total_emission_kg = ckpt_data.get("total_emission_kg", 0.0)
            start_epoch       = resume_ep + 1
            remaining = (epochs - resume_ep) * steps_per_epoch
            if remaining > 0:
                _, scheduler = get_optimizer_scheduler(model, remaining, lr=1e-3)
            print(f"[RESUME] Resuming from epoch {start_epoch}")
            break

    for epoch in range(start_epoch, epochs + 1):
        epoch_tracker = EmissionsTracker(
            project_name=f"{model_name}_e{epoch}",
            output_dir=ARTIFACT_DIR,
            output_file=f"{model_name}_e{epoch}_emissions.csv",
            log_level="error",
            save_to_file=True,
            gpu_ids=_gpu_ids,
        )
        epoch_tracker.start()

        model.train()
        epoch_loss = 0.0
        for images, labels in train_loader:
            images, labels = images.to(DEVICE), labels.to(DEVICE)
            if is_vit:
                images = F.interpolate(images, size=224, mode="bilinear", align_corners=False)
            images, y_a, y_b, lam = cutmix_batch(images, labels)
            optimizer.zero_grad(set_to_none=True)

            with autocast(device_type=DEVICE_TYPE):
                out  = model(images)
                loss = label_smooth_loss(out, y_a, y_b, lam)

            scaler.scale(loss).backward()
            scaler.unscale_(optimizer)
            nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            scaler.step(optimizer)
            scaler.update()

            # Guard: OneCycleLR raises if stepped past total_steps
            if scheduler.last_epoch < scheduler.total_steps:
                scheduler.step()
            epoch_loss += loss.item()

        epoch_emission    = epoch_tracker.stop()
        epoch_emission_kg = epoch_emission if epoch_emission else 0.0
        total_emission_kg += epoch_emission_kg

        val_acc1, val_acc5, _ = evaluate(model, val_loader, use_resize=is_vit)
        avg_loss = epoch_loss / len(train_loader)

        training_curves["train_loss"].append(avg_loss)
        training_curves["val_acc1"].append(val_acc1)
        training_curves["val_acc5"].append(val_acc5)
        training_curves["epoch_emission_kg"].append(epoch_emission_kg)

        if val_acc1 > best_val_acc:
            best_val_acc = val_acc1
            best_state   = deepcopy(model.state_dict())
            torch.save(best_state, ckpt_path)

        # Periodic checkpoint every 10 epochs for crash-recovery
        if epoch % 10 == 0:
            torch.save({
                "epoch":                epoch,
                "model_state_dict":     model.state_dict(),
                "optimizer_state_dict": optimizer.state_dict(),
                "scheduler_state_dict": scheduler.state_dict(),
                "val_acc1":             val_acc1,
                "best_val_acc":         best_val_acc,
                "total_emission_kg":    total_emission_kg,
            }, f"{ARTIFACT_DIR}/{model_name}_epoch{epoch}.pt")

        if epoch % 5 == 0 or epoch == 1:
            print(f"  Epoch {epoch:3d}/{epochs} | Loss: {avg_loss:.4f} | "
                  f"Val Acc@1: {val_acc1:.4f} | Val Acc@5: {val_acc5:.4f} | "
                  f"Emission: {epoch_emission_kg:.6f} kg")

    total_emission = outer_tracker.stop()
    if total_emission:
        total_emission_kg = total_emission

    model.load_state_dict(torch.load(ckpt_path, map_location=DEVICE, weights_only=True))

    test_acc1, test_acc5, avg_lat = evaluate(model, test_loader, use_resize=is_vit)
    preds, labels_arr = get_all_preds_labels(model, test_loader, use_resize=is_vit)
    prec, rec, f1, _  = precision_recall_fscore_support(labels_arr, preds, average="macro", zero_division=0)
    per_cls_acc       = per_class_accuracy(model, test_loader, use_resize=is_vit)
    size_mb           = model_size_mb(model)

    super_acc = {}
    for sc_name, class_ids in SUPERCLASS_MAPPING.items():
        sc_idx   = np.isin(labels_arr, class_ids)
        sc_preds = preds[sc_idx]
        sc_labs  = labels_arr[sc_idx]
        super_acc[sc_name] = float(accuracy_score(sc_labs, sc_preds)) if len(sc_labs) > 0 else 0.0

    green_score = test_acc1 / max(total_emission_kg, 1e-9)

    result = {
        "model":                model_name,
        "type":                 "deep_learning",
        "test_acc1":            round(test_acc1, 4),
        "test_acc5":            round(test_acc5, 4),
        "val_acc1":             round(best_val_acc, 4),
        "precision_macro":      round(float(prec), 4),
        "recall_macro":         round(float(rec), 4),
        "f1_macro":             round(float(f1), 4),
        "inference_latency_ms": round(avg_lat, 4),
        "model_size_mb":        size_mb,
        "total_emission_kg":    round(total_emission_kg, 8),
        "green_score":          round(green_score, 4),
        "n_params_M":           round(n_params, 2),
        "checkpoint":           ckpt_path,
        "timestamp":            datetime.utcnow().isoformat(),
    }

    with open(f"{ARTIFACT_DIR}/{model_name}_training_curves.json", "w") as f:
        json.dump(training_curves, f, indent=2)
    with open(f"{ARTIFACT_DIR}/{model_name}_per_class.json", "w") as f:
        json.dump({"per_class_accuracy": per_cls_acc, "superclass_accuracy": super_acc}, f, indent=2)
    with open(f"{ARTIFACT_DIR}/records.jsonl", "a") as f:
        f.write(json.dumps(result) + "\n")

    print(f"\n[RESULT] {model_name} | Test@1: {test_acc1:.4f} | Test@5: {test_acc5:.4f} | "
          f"F1: {f1:.4f} | Emission: {total_emission_kg:.6f} kg | GreenScore: {green_score:.4f}")

    return model, result, training_curves

# ==============================================================
# SECTION 7: EMBEDDING EXTRACTION & CLASSICAL ML PIPELINE
# ==============================================================

def extract_embeddings(model, loader, use_resize=False):
    model.eval()
    embeddings, all_labels = [], []
    with torch.no_grad():
        for images, labels in loader:
            if use_resize:
                images = F.interpolate(images, size=224, mode="bilinear", align_corners=False)
            images = images.to(DEVICE)
            feats  = model.forward_features(images)
            if feats.dim() == 4:
                feats = feats.mean(dim=[2, 3])
            elif feats.dim() == 3:
                feats = feats[:, 0]   # CLS token for ViT
            embeddings.append(feats.cpu().numpy())
            all_labels.extend(labels.numpy().tolist())
    return np.concatenate(embeddings, axis=0), np.array(all_labels)


def train_classical_models(resnet_model, dl_results):
    """Extract ResNet50 embeddings then train 4 classical ML models."""
    print(f"\n{'='*60}")
    print("[TRAIN] Classical ML Pipeline")
    print(f"{'='*60}")

    _gpu_ids = [] if DEVICE_TYPE == "cpu" else None

    # ── Carbon-track embedding extraction ──────────────────────
    embed_tracker = EmissionsTracker(
        project_name="embedding_extraction",
        output_dir=ARTIFACT_DIR,
        output_file="embedding_emissions.csv",
        log_level="error",
        save_to_file=True,
        gpu_ids=_gpu_ids,
    )
    embed_tracker.start()

    print("[INFO] Extracting ResNet50 embeddings (train)...")
    X_train_raw, y_train = extract_embeddings(resnet_model, embed_loader)
    print("[INFO] Extracting ResNet50 embeddings (test)...")
    X_test_raw,  y_test  = extract_embeddings(resnet_model, test_loader)

    embed_emission = embed_tracker.stop() or 0.0
    print(f"[INFO] Embedding extraction emission: {embed_emission:.6f} kg")
    print(f"[INFO] Train embeddings shape: {X_train_raw.shape}")

    # ── PCA preprocessing ──────────────────────────────────────
    scaler  = StandardScaler()
    pca     = PCA(n_components=PCA_COMPONENTS, random_state=SEED)
    X_train = pca.fit_transform(scaler.fit_transform(X_train_raw))
    X_test  = pca.transform(scaler.transform(X_test_raw))

    joblib.dump(scaler, f"{ARTIFACT_DIR}/scaler.pkl")
    joblib.dump(pca,    f"{ARTIFACT_DIR}/pca.pkl")
    print(f"[INFO] PCA explained variance: {pca.explained_variance_ratio_.sum():.4f}")

    # ── Sub-sample for fast classical ML training ───────────────
    # FIX: MAX_SAMPLES and X_train_small defined INSIDE the function
    # so they are in the correct scope. Previously they were incorrectly
    # placed at module level causing a NameError or scope confusion.
    X_train_small = X_train[:MAX_SAMPLES]
    y_train_small = y_train[:MAX_SAMPLES]
    print(f"[INFO] Training classical models on {len(X_train_small)} samples "
          f"(full train = {len(X_train)})")

    # ── XGBoost params ─────────────────────────────────────────
    xgb_params = dict(
        n_estimators=150,
        max_depth=5,
        learning_rate=0.1,
        eval_metric="mlogloss",
        tree_method="hist",
        random_state=SEED,
        n_jobs=-1,
    )
    if DEVICE_TYPE == "cuda":
        xgb_params["device"] = "cuda"

    # ── Model definitions (ALL inside the function — FIX for scope bug) ──
    # FIX: SVC(rbf) replaced with LinearSVC which is 10-50x faster on large
    # datasets. Wrapped in CalibratedClassifierCV to restore predict_proba
    # compatibility if needed.
    classical_models = {
        "svm": CalibratedClassifierCV(
            LinearSVC(C=1.0, max_iter=2000, random_state=SEED)
        ),
        "rf": RandomForestClassifier(
            n_estimators=100,
            max_depth=20,
            n_jobs=-1,
            random_state=SEED,
        ),
        "xgboost": XGBClassifier(**xgb_params),
        "logreg":  LogisticRegression(
            max_iter=500,
            C=1.0,
            n_jobs=-1,
            random_state=SEED,
        ),
    }

    classical_results = []

    for clf_name, clf in classical_models.items():
        print(f"\n[TRAIN] {clf_name.upper()}...")
        clf_tracker = EmissionsTracker(
            project_name=f"classical_{clf_name}",
            output_dir=ARTIFACT_DIR,
            output_file=f"classical_{clf_name}_emissions.csv",
            log_level="error",
            save_to_file=True,
            gpu_ids=_gpu_ids,
        )
        clf_tracker.start()
        t0 = time.time()
        clf.fit(X_train_small, y_train_small)   # train on sub-sample
        train_time   = time.time() - t0
        clf_emission = clf_tracker.stop() or 0.0
        print(f"[INFO] {clf_name} trained in {train_time:.1f}s")

        t1    = time.time()
        preds = clf.predict(X_test)             # evaluate on full test set
        infer_time_ms = (time.time() - t1) / len(y_test) * 1000

        acc1 = float(accuracy_score(y_test, preds))
        prec, rec, f1, _ = precision_recall_fscore_support(
            y_test, preds, average="macro", zero_division=0
        )

        pkl_path = f"{ARTIFACT_DIR}/{clf_name}.pkl"
        joblib.dump(clf, pkl_path)

        result = {
            "model":                clf_name,
            "type":                 "classical",
            "test_acc1":            round(acc1, 4),
            "test_acc5":            None,
            "precision_macro":      round(float(prec), 4),
            "recall_macro":         round(float(rec), 4),
            "f1_macro":             round(float(f1), 4),
            "inference_latency_ms": round(infer_time_ms, 4),
            "model_size_mb":        round(os.path.getsize(pkl_path) / 1e6, 2),
            "total_emission_kg":    round(clf_emission, 8),
            "green_score":          round(acc1 / max(clf_emission, 1e-9), 4),
            "train_time_s":         round(train_time, 2),
            "checkpoint":           pkl_path,
            "timestamp":            datetime.utcnow().isoformat(),
        }

        with open(f"{ARTIFACT_DIR}/records.jsonl", "a") as f:
            f.write(json.dumps(result) + "\n")

        classical_results.append(result)
        print(f"  [{clf_name}] Acc@1: {acc1:.4f} | F1: {f1:.4f} | "
              f"Emission: {clf_emission:.6f} kg | Latency: {infer_time_ms:.4f} ms")

    # Return full X_train/X_test (not the sub-sampled version) for ACO
    return classical_results, X_train, X_test, y_train, y_test

# ==============================================================
# SECTION 8: ANT COLONY OPTIMIZATION (ELITIST ACO)
# ==============================================================

class ACOConfigSearch:
    """
    Elitist ACO for model/hyperparameter configuration selection.
    Objective: J = emission_kg + lambda * (1 - accuracy) + carbon_penalty
    """

    def __init__(self, all_results, lambda_carbon=LAMBDA_CARBON,
                 n_ants=ACO_ANTS, n_iterations=ACO_ITERATIONS,
                 alpha=1.0, beta=2.0, rho=0.1, elitist_k=3,
                 carbon_budget=1.0):
        self.results       = all_results
        self.lambda_carbon = lambda_carbon
        self.n_ants        = n_ants
        self.n_iter        = n_iterations
        self.alpha         = alpha
        self.beta          = beta
        self.rho           = rho
        self.elitist_k     = elitist_k
        self.carbon_budget = carbon_budget

        self.model_names = [r["model"] for r in all_results]
        self.lr_options  = [1e-4, 5e-4, 1e-3, 5e-3]
        self.wd_options  = [1e-5, 1e-4, 1e-3]
        self.ep_options  = [50, 75, 100]

        n_m = len(self.model_names)
        n_l = len(self.lr_options)
        n_w = len(self.wd_options)
        n_e = len(self.ep_options)

        self.tau_model = np.ones(n_m)
        self.tau_lr    = np.ones(n_l)
        self.tau_wd    = np.ones(n_w)
        self.tau_ep    = np.ones(n_e)

        gs = np.array([r.get("green_score", 1.0) for r in all_results])
        gs = np.where(gs == 0, 1e-6, gs)
        self.eta_model = gs / gs.sum()
        self.eta_lr    = np.array([1/v for v in self.lr_options]); self.eta_lr /= self.eta_lr.sum()
        self.eta_wd    = np.array([1/v for v in self.wd_options]); self.eta_wd /= self.eta_wd.sum()
        self.eta_ep    = np.array(self.ep_options, dtype=float);   self.eta_ep /= self.eta_ep.sum()

        self.history      = []
        self.best_config  = None
        self.best_fitness = float("inf")

    def _select(self, tau, eta):
        weights = (tau ** self.alpha) * (eta ** self.beta)
        weights = np.maximum(weights, 1e-10)
        probs   = weights / weights.sum()
        return int(np.random.choice(len(tau), p=probs))

    def _fitness(self, config):
        r        = self.results[config["model_idx"]]
        emission = r.get("total_emission_kg", 1.0)
        accuracy = r.get("test_acc1", 0.0)
        penalty  = 10.0 if emission > self.carbon_budget else 0.0
        return emission + self.lambda_carbon * (1 - accuracy) + penalty

    def _adaptive_evaporation(self, iteration):
        return self.rho + 0.3 * (iteration / self.n_iter)

    def run(self):
        print(f"\n{'='*60}")
        print("[ACO] Starting Elitist Ant Colony Optimization")
        print(f"      Ants: {self.n_ants} | Iterations: {self.n_iter} | λ: {self.lambda_carbon}")
        print(f"{'='*60}")

        _gpu_ids = [] if DEVICE_TYPE == "cpu" else None
        aco_tracker = EmissionsTracker(
            project_name="aco_optimization",
            output_dir=ARTIFACT_DIR,
            output_file="aco_emissions.csv",
            log_level="error",
            save_to_file=True,
            gpu_ids=_gpu_ids,
        )
        aco_tracker.start()

        for it in range(1, self.n_iter + 1):
            ant_solutions = []
            for _ in range(self.n_ants):
                config = {
                    "model_idx": self._select(self.tau_model, self.eta_model),
                    "lr_idx":    self._select(self.tau_lr,    self.eta_lr),
                    "wd_idx":    self._select(self.tau_wd,    self.eta_wd),
                    "ep_idx":    self._select(self.tau_ep,    self.eta_ep),
                }
                config["fitness"] = self._fitness(config)
                ant_solutions.append(config)

            ant_solutions.sort(key=lambda x: x["fitness"])
            elite = ant_solutions[:self.elitist_k]

            if ant_solutions[0]["fitness"] < self.best_fitness:
                self.best_fitness = ant_solutions[0]["fitness"]
                self.best_config  = deepcopy(ant_solutions[0])

            rho_t = self._adaptive_evaporation(it)
            self.tau_model *= (1 - rho_t)
            self.tau_lr    *= (1 - rho_t)
            self.tau_wd    *= (1 - rho_t)
            self.tau_ep    *= (1 - rho_t)

            for sol in elite:
                deposit = 1.0 / max(sol["fitness"], 1e-9)
                self.tau_model[sol["model_idx"]] += deposit
                self.tau_lr   [sol["lr_idx"]   ] += deposit
                self.tau_wd   [sol["wd_idx"]   ] += deposit
                self.tau_ep   [sol["ep_idx"]   ] += deposit

            for tau in [self.tau_model, self.tau_lr, self.tau_wd, self.tau_ep]:
                np.clip(tau, 0.01, 10.0, out=tau)

            best_model_name = self.model_names[self.best_config["model_idx"]]
            self.history.append({
                "iteration":    it,
                "best_fitness": round(self.best_fitness, 6),
                "best_model":   best_model_name,
                "rho_adaptive": round(rho_t, 4),
                "tau_model":    self.tau_model.tolist(),
            })

            if it % 5 == 0 or it == 1:
                print(f"  Iter {it:3d}/{self.n_iter} | Best Fitness: {self.best_fitness:.6f} | "
                      f"Best Model: {best_model_name} | ρ: {rho_t:.4f}")

        aco_emission = aco_tracker.stop() or 0.0
        print(f"\n[ACO] Done. Best fitness: {self.best_fitness:.6f} | "
              f"Best model: {self.model_names[self.best_config['model_idx']]}")
        print(f"[ACO] Emission during optimization: {aco_emission:.6f} kg")

        resolved = {
            "model":           self.model_names[self.best_config["model_idx"]],
            "lr":              self.lr_options [self.best_config["lr_idx"]],
            "weight_decay":    self.wd_options [self.best_config["wd_idx"]],
            "epochs":          self.ep_options [self.best_config["ep_idx"]],
            "fitness":         self.best_fitness,
            "aco_emission_kg": round(aco_emission, 8),
        }

        return resolved, self.history, {
            "tau_model": self.tau_model.tolist(),
            "tau_lr":    self.tau_lr.tolist(),
            "tau_wd":    self.tau_wd.tolist(),
            "tau_ep":    self.tau_ep.tolist(),
        }

# ==============================================================
# SECTION 9: LEADERBOARD & REPORTING
# ==============================================================

def build_leaderboard(all_results):
    ranked = sorted(deepcopy(all_results), key=lambda x: x.get("test_acc1", 0), reverse=True)
    for i, r in enumerate(ranked):
        r["rank"] = i + 1
    return ranked

def print_leaderboard(leaderboard):
    table = PrettyTable()
    table.field_names = ["Rank", "Model", "Type", "Acc@1", "Acc@5", "F1",
                         "Emission(kg)", "GreenScore", "Size(MB)"]
    for r in leaderboard:
        table.add_row([
            r.get("rank", "-"),
            r["model"],
            r["type"],
            f"{r.get('test_acc1', 0):.4f}",
            f"{r.get('test_acc5', 0) or 0:.4f}",
            f"{r.get('f1_macro', 0):.4f}",
            f"{r.get('total_emission_kg', 0):.6f}",
            f"{r.get('green_score', 0):.4f}",
            f"{r.get('model_size_mb', 0):.2f}",
        ])
    print("\n[LEADERBOARD]")
    print(table)

# ==============================================================
# SECTION 10: ARTIFACT CONSOLIDATION & ZIP
# ==============================================================

def consolidate_emissions_csv():
    frames = []
    for csv_file in Path(ARTIFACT_DIR).glob("*.csv"):
        # KNN has been removed from the pipeline — skip its stale emission log
        if csv_file.name.startswith("classical_knn"):
            print(f"[INFO] Skipping removed-model emission log: {csv_file.name}")
            continue
        try:
            df = pd.read_csv(csv_file)
            df["source_file"] = csv_file.name
            frames.append(df)
        except Exception:
            pass
    if frames:
        master = pd.concat(frames, ignore_index=True)
        master.to_csv(f"{ARTIFACT_DIR}/emissions.csv", index=False)
        print(f"[INFO] Consolidated emissions CSV: {len(master)} rows")
    else:
        pd.DataFrame().to_csv(f"{ARTIFACT_DIR}/emissions.csv", index=False)


def save_all_artifacts(leaderboard, aco_best, aco_history, aco_pheromones, all_training_curves):
    with open(f"{ARTIFACT_DIR}/leaderboard.json", "w") as f:
        json.dump(leaderboard, f, indent=2)
    with open(f"{ARTIFACT_DIR}/aco_logs.json", "w") as f:
        json.dump({"best_config": aco_best, "history": aco_history,
                   "pheromones": aco_pheromones}, f, indent=2)
    with open(f"{ARTIFACT_DIR}/training_curves.json", "w") as f:
        json.dump(all_training_curves, f, indent=2)
    print(f"[INFO] All JSON artifacts saved to {ARTIFACT_DIR}/")

def zip_artifacts():
    zip_path = "./carbon_aco_artifacts.zip"
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for fpath in Path(ARTIFACT_DIR).rglob("*"):
            if fpath.is_file():
                zf.write(fpath, arcname=fpath.relative_to(ARTIFACT_DIR))
    size_mb = os.path.getsize(zip_path) / 1e6
    print(f"[INFO] Artifacts zipped: {zip_path} ({size_mb:.2f} MB)")
    return zip_path

# ==============================================================
# SECTION 11: MAIN EXECUTION PIPELINE
# ==============================================================
# NOTE: On Kaggle, __name__ is never "__main__" — notebooks run as modules.
# We execute directly at module scope (no if __name__ guard).

print("\n" + "="*60)
print("  Carbon-Aware ACO CIFAR-100 — Phase 1 Pipeline")
print("="*60)

all_results      = []
all_dl_models    = {}
all_train_curves = {}

# ── STEP 1: Train deep learning models ──────────────────────
for model_name in ["resnet50", "efficientnet_b3", "vit_tiny"]:
    try:
        model, result, curves = train_dl_model(model_name, epochs=EPOCHS)
        all_results.append(result)
        all_dl_models[model_name] = model
        all_train_curves[model_name] = curves
    except Exception as e:
        print(f"[ERROR] Failed training {model_name}: {e}")
        import traceback; traceback.print_exc()

# ── STEP 2: Classical ML pipeline ───────────────────────────
if "resnet50" in all_dl_models:
    try:
        classical_results, X_tr, X_te, y_tr, y_te = train_classical_models(
            all_dl_models["resnet50"], all_results
        )
        all_results.extend(classical_results)
    except Exception as e:
        print(f"[ERROR] Classical ML pipeline failed: {e}")
        import traceback; traceback.print_exc()
else:
    print("[WARN] ResNet50 not trained; skipping classical ML pipeline.")
    X_tr = X_te = y_tr = y_te = None

# ── STEP 3: ACO Optimization ────────────────────────────────
if not all_results:
    print("[WARN] No results — skipping ACO.")
    aco_best, aco_history, aco_pheromones = {}, [], {}
else:
    try:
        aco = ACOConfigSearch(
            all_results=all_results,
            lambda_carbon=LAMBDA_CARBON,
            n_ants=ACO_ANTS,
            n_iterations=ACO_ITERATIONS,
            elitist_k=3,
            carbon_budget=2.0,
        )
        aco_best, aco_history, aco_pheromones = aco.run()
        print(f"\n[ACO] Recommended config: {aco_best}")
    except Exception as e:
        print(f"[ERROR] ACO failed: {e}")
        import traceback; traceback.print_exc()
        aco_best, aco_history, aco_pheromones = {}, [], {}

# ── STEP 4: Leaderboard ─────────────────────────────────────
leaderboard = build_leaderboard(all_results)
print_leaderboard(leaderboard)

# ── STEP 5: Save artifacts ───────────────────────────────────
consolidate_emissions_csv()
save_all_artifacts(leaderboard, aco_best, aco_history, aco_pheromones, all_train_curves)

# ── STEP 6: Per-class consolidation ─────────────────────────
per_class_all = {}
for model_name in all_dl_models:
    pc_path = f"{ARTIFACT_DIR}/{model_name}_per_class.json"
    if os.path.exists(pc_path):
        with open(pc_path) as f:
            per_class_all[model_name] = json.load(f)
with open(f"{ARTIFACT_DIR}/per_class_results.json", "w") as f:
    json.dump(per_class_all, f, indent=2)

# ── STEP 7: Zip ─────────────────────────────────────────────
zip_path = zip_artifacts()

# ── STEP 8: Final summary ────────────────────────────────────
print("\n" + "="*60)
print("  PIPELINE COMPLETE — SUMMARY")
print("="*60)
print(f"  Models trained:    {len([r for r in all_results if r['type'] == 'deep_learning'])}")
print(f"  Classical models:  {len([r for r in all_results if r['type'] == 'classical'])}")
print(f"  ACO recommended:   {aco_best.get('model', 'N/A')}")
print(f"  Total experiments: {len(all_results)}")
if all_results:
    best     = max(all_results, key=lambda x: x.get("test_acc1", 0))
    greenest = max(all_results, key=lambda x: x.get("green_score", 0))
    print(f"  Best model:        {best['model']} (Acc@1={best['test_acc1']:.4f})")
    print(f"  Greenest model:    {greenest['model']} (GreenScore={greenest['green_score']:.4f})")
print(f"  Artifacts saved:   {ARTIFACT_DIR}/")
print(f"  Download zip:      {zip_path}")
print("="*60)